### ISSUE TITLE
태그를 2개 추가할 수 있을까요?

### ISSUE THREAD

**Issue by Murianwind** [staiji/citywaste_korea#2]
RFID 태그가 2개인 경우 태그를 2개 추가하도록 해주실 수 있나요?

폴더를 다른 이름으로 복사해 붙여 넣어서 센서를 하나 더 추가할 수도 있지만.. 그렇게 하면 너무 지저분해져서..

혹시 태그를 2개 이상 추가하도록 해주실 수 있나요?

추가하면 혹시 수수료도 추가해주실 수 있나요?

**Comment by staiji** [comment]
```
  - platform: citywaste_korea
    tagprintcd: KKRW0B1C000000001
    aptdong: 101
    apthono: 1004
  - platform: citywaste_korea
    name: mom
    tagprintcd: KKRW0B1C000000002
    aptdong: 102
    apthono: 2004
```

이런식으로 설정하시면 지금도 2개 이상 추가 가능합니다.
저도 현재 태그 두개를 동시에 사용중입니다.

수수료의 경우 지역마다 다르다고 알고 있습니다.
template sensor를 추가해서 사용하시는것을 추천드립니다.

향후에 UI에서 설정이 가능한 config flow를 적용하게 되면, 본인 지역의 수수료를 입력해서 설정하는것을 고려해 보겠습니다.
감사합니다.

**Comment by Murianwind** [comment]
아.. 저는 1집에 2개의 태그를 쓰는 경우 위처럼 등록했을 때 구성요소는 하나만 나와서 하나는 인식이 안되는줄 알았는데.. 아닌가보네요.. 그냥 태그를 2개 등록하면 알아서 전체 킬로그램과 마지막 킬로그램을 불러오는건가보네요.

전 태그 별로 버린 음식물 쓰레기와 2개의 태그를 합산한 용량을 볼 수 있는건가 했는데.. 아닌가 보네요..

https://www.citywaste.or.kr/

여기에 접속해서 로그인하면 나의 수수료를 조회할 수 있는데.. 그걸 크롤링하는건 어려운건가 보군요..

만들어주신 센서 잘 사용하고 있습니다.

고맙습니다.

**Comment by staiji** [comment]
제가 요청사항을 잘못 이해했네요. 죄송합니다.
혹시 태그가 여러개면 간편조회에서 세대별 합산이 아니라 해당 태그로 배출한것만 보여주는건가요?
비밀번호로 배출해도 태그로 배출한것처럼 나오는것으로 알고 있는데 태그가 여러개일때는 어떤지 모르겠습니다.

수수료의 경우 현재는 간편조회 페이지를 사용하여 구현된 센서이기 때문에 다른 방법이 필요한 기능은 당장 추가가 어려울것 같습니다.

감사합니다.

**Comment by staiji** [comment]
그리고 위에 올려드린 설정 예제는 2개의 세대인 경우의 예제입니다.

**Comment by Murianwind** [comment]
세대별 합산으로 나오기는 합니다. 저는 그냥 좀 더 세세하게 볼 수 있는건가 해서 질문을 남겨보았습니다. 

수수료 계산하는건 저도 좀 생각해봐야겠습니다. 수수료 계산하는 식이나 기본 수수료 정보 찾기가 너무 어렵네요..

그래서 홈페이지에 있는 나의 수수료를 땡겨오면 제일 편할거라고 생각했는데.. 그게 아닌가보네요..

어쨌든.. 질문에 답변 남겨주셔서 고맙습니다

즐거운 하루 되세요.
