### ISSUE TITLE
컴포넌트가 데이터를 불러오지 못합니다.

### ISSUE THREAD

**Issue by Murianwind** [staiji/citywaste_korea#3]
이 오류는 사용자 통합구성요소에서 발생했습니다.

Logger: custom_components.citywaste_korea.sensor
Source: custom_components/citywaste_korea/sensor.py:132
Integration: citywaste_korea (documentation)
First occurred: 08:06:17 (1 occurrences)
Last logged: 08:06:17

Error parsing list

와 같은 에러메시지가 출력되고 데이터를 불러오지 못합니다.

테스트 해본 결과 센서 설정의 tagprintcd 값을 제대로 불러오지 못하는 것 같습니다.

tagprintcd 값을 지우고 HA를 재시작하면 컴포넌트가 동작을 하는데.. tagprintcd 값을 입력하고 HA를 재시작하면 에러 로그가 출력됩니다.

현재 HA 환경은 아래와 같고 컴포넌트는 최신버전이 설치되어 있습니다.

Home Assistant 2022.12.8
Supervisor 2022.12.1
Operating System 9.4
Frontend 버전: 20221213.1 - latest

**Comment by staiji** [comment]
서버에서 referer를 확인하도록 변경된 이후 기존의 0.1.1 버전에서 오류가 발생했습니다.
0.1.2 에서 header에 referer를 추가하도록 변경하여 수정되었고 제가 테스트한 두군데 환경에서는 지금까지 한번의 오류도 없이 정상 작동중입니다.
0.1.2 버전에서도 문제가 발생한다면 완전히 삭제후 다시 설치해 보시길 부탁드립니다.

**Comment by staiji** [comment]
다시 확인해보니 배출횟수가 10번이 넘는 경우에 문제가 발생하는 것으로 보입니다.
해당사항 수정하겠습니다
